import pandas as pd

df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_1_PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_1_PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_2_PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_2_PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_3_PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_3_PM1_melted.csv", index=False)

df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_1_PM3b.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_1_PM3b_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_2_PM3b.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_2_PM3b_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_3_PM3b.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_3_PM3b_melted.csv", index=False)
