import pandas as pd

df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y1P062 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y1P062 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y1P126 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y1P126 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y1P188 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y1P188 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y2P062 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y2P062 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y2P126 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y2P126 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y2P188 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y2P188 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y3P062 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y3P062 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y3P126 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y3P126 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/Y3P188 - PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/Y3P188 - PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_1_PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_1_PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_2_PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_2_PM1_melted.csv", index=False)
df = pd.read_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/1_Samples_csv_files/M1152_3_PM1.csv")
melted_df = pd.melt(df, id_vars=['Hour'], var_name='Type', value_name='Value')
melted_df.to_csv("/Users/johnmunnoch/Documents/Work/4_2023-onwards/0-LTEE_continued/Biolog_community_1k-2k-3k_PM1-PM3b/Final_processing/2_melted_data/M1152_3_PM1_melted.csv", index=False)